"use client";

import { useParams } from "next/navigation";
import { Metadata } from "next";
import Image from "next/image";
import Head from "next/head";
import Breadcrumbs from "../../Breadcrumbs/Breadcrumbs";
import posts from "../data.json";

export const metadata: Metadata = {
  title: "Chi tiết bài viết",
  description: "Generated by create next app",
};

const PostDetailPage = () => {
  const { id } = useParams();

  const breadcrumbs = [
    { label: "Home", href: "/" },
    { label: "Posts", href: "/posts" },
    { label: `Post ${id}`, href: `/posts/${id}` },
  ];

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: breadcrumbs.map((crumb, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: crumb.label,
      item: `https://yourdomain.com${crumb.href}`,
    })),
  };

  const post = posts.find((post) => post.id.toString() === id);

  return (
    <div>
      <Head>
        <script type="application/ld+json">{JSON.stringify(jsonLd)}</script>
      </Head>
      <Breadcrumbs breadcrumbs={breadcrumbs} />
      <h1>Chi tiết bài viết có Id = {id}</h1>
      {post ? (
        <div
          style={{
            border: "1px solid #ddd",
            borderRadius: "5px",
            padding: "10px",
            maxWidth: "490px",
          }}
        >
          <Image
            src={post.thumbnailUrl}
            alt={post.title}
            width={150}
            height={150}
            style={{ borderRadius: "5px" }} // Quản lý bố cục hình ảnh
            loading="lazy"
          />
          <p>{post.title}</p>
          <p>{post.content}</p>{" "}
        </div>
      ) : (
        <p>Không tìm thấy bài viết!</p>
      )}
    </div>
  );
};

export default PostDetailPage;
