import { Metadata } from "next";
import Image from "next/image";
import Head from "next/head";
import Breadcrumbs from "../Breadcrumbs/Breadcrumbs"; // Đường dẫn đến component Breadcrumbs
import posts from "./data.json";

export const metadata: Metadata = {
  title: "Danh sách bài viết",
  description: "Generated by create next app",
};

const PostsPage = () => {
  const breadcrumbs = [
    { label: "Home", href: "/" },
    { label: "Posts", href: "/posts" },
  ];

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: breadcrumbs.map((crumb, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: crumb.label,
      item: `https://yourdomain.com${crumb.href}`,
    })),
  };

  return (
    <div>
      <Head>
        <script type="application/ld+json">{JSON.stringify(jsonLd)}</script>
      </Head>
      <Breadcrumbs breadcrumbs={breadcrumbs} />
      <h1>Danh sách bài viết</h1>
      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: "20px",
          maxWidth: "490px",
        }}
      >
        {posts.map((post) => (
          <div
            key={post.id}
            style={{
              border: "1px solid #ddd",
              borderRadius: "5px",
              padding: "10px",
              width: "150px",
              textAlign: "center",
            }}
          >
            <Image
              src={post.thumbnailUrl}
              alt={post.title}
              width={150}
              height={150}
              layout="responsive"
              style={{ borderRadius: "5px" }}
              loading="lazy"
            />
            <p>{post.title}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default PostsPage;
